---
name: build and upload extension

on:
  push:
    branches: [master]
jobs:
  build-deploy:
    name: Build and Deploy extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install -g tfx-cli
    - run: npm ci
      working-directory: mvn-mirror/v0
    - run: tsc
      working-directory: mvn-mirror/v0
    - run: tfx login -u ${URL} -t ${TOKEN}
      env:
        URL: ${{ secrets.URL }}
        TOKEN: ${{ secrets.TOKEN }}
    - run: tfx extension create
    - run: tfx extension publish --token ${TOKEN} --no-wait-validation
      env:
        URL: ${{ secrets.URL }}
        TOKEN: ${{ secrets.TOKEN }}
