---
name: build and upload extension

on:
  push:
    branches: [ $default-branch ]

jobs:
  build-deploy:
    # Name the Job
    name: Build and Deploy extension
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install -g tfx-cli
    - run: cd azure-pipelines-maven-mirror/mvn-mirror/v0
    - run: npm ci
    - run: cd ${GITHUB_WORKSPACE}
    - run: tfx extension create --manifest-globs ./vss-extension.json
